apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: qa
  namespace: default
spec:
  acme:
    config:
      - domains:
          - www.qa.bct.trade
          - auth.qa.bct.trade
          - login.qa.bct.trade
        http01:
          ingressClass: nginx
  commonName: www.qa.bct.trade
  dnsNames:
    - www.qa.bct.trade
    - auth.qa.bct.trade
    - login.qa.bct.trade
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: qa
